# © 2024 Microglot LLC
# SPDX-License-Identifier: CC-BY-SA-4.0

FROM docker.io/debian:bookworm

ENV TZ=Etc/UTC

RUN apt-get update && apt-get upgrade --yes && \
    apt-get install --yes wget curl make jq git vim man \
                          build-essential nodejs npm \
                          pipx \
                          shfmt shellcheck \
                          sudo bash-completion && \
    pipx install reuse

# Create a non-root user so linux users can run the container as the current
# OS user. See https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user
# and https://github.com/devcontainers/spec/blob/main/docs/specs/devcontainer-reference.md#container-creation
# for more information.
ARG USERNAME=mglot
ARG USER_UID=1010
ARG USER_GID=1010

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
